<?php

$api_key = $this->method->getConfigData('api_key');

//$method_array = $this->getPaymentMethods($api_key);

//$method_array = array();
$quote = Mage::getModel('checkout/session')->getQuote();
$quoteData = $quote->getData();
$grandTotal = $quoteData['grand_total'];
$currency = $quoteData['base_currency_code'];
$modde    =  $this->method->getConfigData('transaction_mode');

?>
<link rel="stylesheet" href="https://sdk.ceevo.com/ceevo.css">


<!-- <form id="ceevo-form" action="checkout/onepage/index" method="post">
 -->
 <div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">

  <input type="hidden" id="token_hidden_input" name="token_hidden_input">
  <input type="hidden" id="session_hidden_input" name="session_hidden_input">
  <input type="hidden" id="method_code" name="method_code">
  <input type="hidden" id="3dsecure" name="3dsecure" value="false">
  <input type="hidden" id="apikey" name="apikey" value="<?php echo trim($api_key);?>">
  <input type="hidden" id="paymode" name="paymode" value="<?php echo $modde; ?>">
  <input type="hidden" id="idprice" name="idprice" value="<?php echo $grandTotal; ?>"> 
  <input type="hidden" id="idcurr" name="idcurr" value="<?php echo $currency; ?>">
   
</div>

<!-- </form> -->
